### PR TITLE
update to polkadot v1.12.0

### PR DESCRIPTION
**Pull request by R9295**

### CODE REVIEW

**Comment by R9295** [comment]
@louismerlin why isn't the CI running here?

**Review by louismerlin — APPROVED** [review]

**Comment by louismerlin** [comment]
There should be no need to update the asset-hub/kusama/coretime fuzzers, the versions of `runtimes` and `polkadot-sdk` are not correlated.

**Comment by R9295** [comment]
yeah, just saw there was no new release

**Comment by louismerlin** [comment]
I can't find the "Approve and run" button for CI stuff, one sec

**Comment by R9295** [comment]
@louismerlin the check ran

**Pull request merged**
